version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: logger
      POSTGRES_PASSWORD: loggerpass
      POSTGRES_DB: devlog
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  devlogger:
    build: .
    ports:
      - "50051:50051"
    depends_on:
      - db
      - redis

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
